### PR TITLE
Beta banner

### PR DESCRIPTION
**Pull request by potatodepaulo**
Adding a banner to the top of Studio to announce the beta program. 
Note: This is a hard-coded, temporary solution. 

The long term solution will include an ability for users to dismiss.

### Screenshots/Videos (OPTIONAL)
Screenshot 2019-07-10 10 40 28

### CODE REVIEW

**Comment by vgrichina** [comment]
1) Can you rebase to only leave "hack for beta program announcement" commit in PR?
2) Purple link looks very low contrast. Wonder if black or white looks better.
3) Should copy be more specific? E.g. I planned to include following in near-shell:
> NOTE: NEAR CLI is still in beta.  Get in touch with our developers on Discord: [link] if you have any problems. Register at https://nearprotocol.com/beta to get extended support.

**Comment by potatodepaulo** [comment]
Other colors look pretty bad. I think purple is the choice, at least for right now.

**Comment by vgrichina** [comment]
@potatodepaulo looks like tests need to be updated and few lint fixes needed (see gitlab)

**Comment by potatodepaulo** [comment]
There have been tons of commits before. Looks like Gitlab CI has failed since nightshade merge. Do these need to run for us to deploy just the banner?

**Pull request merged**
