### PR TITLE
Update templates to new AS compiler and update nearlib version

### PR DESCRIPTION
**Pull request by evgenykuzyakov**
Update templates to use https://github.com/nearprotocol/assemblyscript/pull/26
Nearlib https://github.com/nearprotocol/nearcore/pull/773

### CODE REVIEW

**Comment by potatodepaulo** [comment]
I spot checked this by trying to run locally. Neither approaches to build work on local. This is fine if it's running in studio alright, but I want to try to fix the local issues.

npm run build
near build

**Comment by potatodepaulo** [comment]
> I spot checked this by trying to run locally. Neither approaches to build work on local. This is fine if it's running in studio alright, but I want to try to fix the local issues.

For `near build` I think it's actually just a versioning problem with near-shell.

**Comment by evgenykuzyakov** [comment]
> I spot checked this by trying to run locally. Neither approaches to build work on local. This is fine if it's running in studio alright, but I want to try to fix the local issues.

I think it's unrelated to the change I made. We need to list dependencies in the package.json and update "build" script to work with near-shell correctly.

**Comment by potatodepaulo** [comment]
! [approved](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM46L5NojCYFD3J_Sl5jKdePJOn_6s_wEREBK4QXcOcSXShgYj)

**Pull request merged**
