### PR TITLE
lint templates

### PR DESCRIPTION
**Pull request by chadoh**
With my editor configured to automatically inspect the project's lint
settings, I got many errors when looking around templates/01. It turns
out that my linter did not notice that the `/templates` directory was
configured to be ignored.

After playing with changing our configuration to lint the templates as
well, I ran into various problems with other stages in our build process
that, given that this version of NEAR Studio will be obsolete soon, do
not seem worth diagnosing and fixing.

Instead, this change updates one lint config setting (stop requiring comment
header attributing file to "Mozilla Foundation" or "the Public Domain")
and uses `tslint --fix` to automatically fix all issues found in the
templates.

The templates still won't be linted by our (current) automated
processes, but this gets them into a stronger spot for now

### CODE REVIEW

**Comment by chadoh** [comment]
Why is renderbot adding the same comment over and over again?

**Comment by vgrichina** [comment]
> use @typescript-eslint/parser to prevent errors on the import line

hmm, is @typescript-eslint working well with AssemblyScript?

**Comment by chadoh** [comment]
@vgrichina I just retried this branch with the `@typescript-eslint/parser` configuration removed and everything is working now – I think something else must have been messed up with my environment when I was running this project on Thursday.

**Comment by vgrichina** [comment]
@chadoh I think we should actually care for these:
- stop preferring const to let
- don't care when there's no space between the // and the comment text

Existing violations should be possible to fix with `eslint --fix`, right?

**Comment by chadoh** [comment]
> Existing violations should be possible to fix with eslint --fix, right?

I've updated it; thanks for the request. Getting it to work correctly required me to dig in deeper and figure out why `yarn lint` wasn't catching these issues – it seems the linter built into my editor didn't notice that our `tsconfig` was ignoring the templates directory, so my editor was being more strict than our actual project settings.

However, it was straightforward to add linting to our templates, and `tslint --fix` was able to fix all the issues found. Let me know what you think of this updated PR, @vgrichina

**Comment by chadoh** [comment]
@vgrichina I got the build passing here – after multiple configuration challenges, I've simplified this PR to only fix the issues found by the linter in the templates, without adding template-linting to our actual build process. Given that these templates may find a new home soon, continuing to fight with the other build steps that kept breaking didn't seem worth continued effort.

Let me know if you think this is ready to merge.

**Pull request merged**
